# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
dist: xenial
language: python
env:
- FLASK_APP=autoapp.py FLASK_DEBUG=1 REDIS=redis://foo
python:
  - 3.6
  - 3.7
  - 3.7-dev
  - 3.8-dev
  - nightly
services:
  - docker
install:
  - sudo apt-get install libarchive-dev
  - pip install -r requirements.txt
script:
  - pip check
  - flask test
  - PYTHON_VERSION=`python --version|head -n1|cut -d' ' -f2|cut -d '+' -f1` docker-compose build
#before_script:
#  - flask lint

#deploy:
#  provider: pypi
#  user: $PYPI_USER
#  password: $PYPI_PASSWORD
#  after_deploy:
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#   - docker build -f Dockerfile -t $REPO:$COMMIT .
#   - docker tag $REPO:$COMMIT $REPO:$TAG
#   - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
#   - docker push USER/REPO
#  on:
#    branch: master
#    tags: true
