# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
env:
- FLASK_APP=autoapp.py FLASK_DEBUG=1
- REDIS=foo
python:
  - 3.6
#  - 3.7
services:
  - docker
install:
  - pip install -r requirements.txt
  - nvm install 6.10
  - nvm use 6.10
  - npm install
script:
  - flask test
before_script:
  - npm run lint
  - npm run build
  - flask lint
deploy:
  provider: script
  script:
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
   - docker build -f Dockerfile -t $REPO:$COMMIT .
   - docker tag $REPO:$COMMIT $REPO:$TAG
   - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
   - docker push USER/REPO
  on:
    branch: release
