version: '2'
services:
  alembic:
    build:
        context: .
        args:
            PYTHON_VERSION: 3.11.1
    depends_on:
      - db
    command: alembic upgrade head
  web:
    restart: on-failure
    build:
        context: .
        args:
            PYTHON_VERSION: 3.11.1
    environment:
      - REDIS=redis://redis:6379/0
      - REDIS_CELERY=redis://redis:6379/1
      - MONGO=mongodb://mongo:27017/
      - TZ=Europe/Prague
      - LOGZIO_TOKEN=ZwNgGaJBmJaONhMeCEIlwCNbeQKZDnlk
      - DB=postgresql+psycopg2://postgres:example@db:5432/postgres
    volumes:
      - ./graphs.txt:/tmp/graphs.txt
    command: gunicorn -w 4 -b 0.0.0.0:8000 --log-level debug app:app
    ports:
      - "8088:8000"
    depends_on:
     - celery
     - redis
     - mongo
     - db
     - alembic
  celery:
    restart: always
    build:
        context: .
        args:
            PYTHON_VERSION: 3.11.1
    environment:
      - REDIS=redis://redis:6379/0
      - REDIS_CELERY=redis://redis:6379/1
      - MONGO=mongodb://mongo:27017/
      - TZ=Europe/Prague
      - LOGZIO_TOKEN=ZwNgGaJBmJaONhMeCEIlwCNbeQKZDnlk
      - DB=postgresql+psycopg2://postgres:example@db:5432/postgres
    volumes:
      - ./exclude.txt:/tmp/exclude.txt
    command: celery -A tsa.celery worker -l debug -Q high_priority,default,query,low_priority -c 4
    depends_on:
      - redis
      - mongo
      - db
      - alembic
  beat:
    restart: always
    build:
        context: .
        args:
            PYTHON_VERSION: 3.11.1
    environment:
      - REDIS=redis://redis:6379/0
      - REDIS_CELERY=redis://redis:6379/1
      - MONGO=mongodb://mongo:27017/
      - TZ=Europe/Prague
      - LOGZIO_TOKEN=ZwNgGaJBmJaONhMeCEIlwCNbeQKZDnlk
      - DB=postgresql+psycopg2://postgres:example@db:5432/postgres
    command: celery -A tsa.celery beat -l warning
    depends_on:
      - redis
      - mongo
      - db
      - alembic
  redis:
    restart: on-failure
    image: "redis:alpine"
    ports:
      - "6379:6379"
  mongo:
    restart: on-failure
    image: "mongo"
    ports:
      - "8081:8081"
      - "27017:27017"
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"