version: '3.3'
services:
  web:
    build:
        context: .
        args:
            PYTHON_VERSION: ${PYTHON_VERSION}
    environment:
      - REDIS=redis://redis:6379/0
    ports:
      - "80:8000"
    depends_on:
      - celery
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  celery:
    build:
        context: .
        args:
            PYTHON_VERSION: ${PYTHON_VERSION}
    environment:
      - REDIS=redis://redis:6379/0
    user: nobody
    depends_on:
      - redis
    command: celery worker -l info -A tsa.celery --pool gevent --concurrency=500
