version: '2'
services:
  web:
    restart: on-failure
    build:
        context: .
        args:
            PYTHON_VERSION: 3.8.7
    environment:
      - REDIS=redis://10.114.0.2:6379/0
      - REDIS_CELERY=redis://10.114.0.2:6379/1
      - MONGO=mongodb://10.114.0.2:27017/
      - STATSD_HOST=graphite
    volumes:
      - /root/data/log:/log
    ports:
      - "8088:8000"
    depends_on:
     - celery
    command: gunicorn -k gevent -w 4 -b 0.0.0.0:8000 --log-level info --log-file /log/gunicorn.log autoapp:app
  celery:
    restart: always
    build:
        context: .
        args:
            PYTHON_VERSION: 3.8.7
    environment:
      - REDIS=redis://10.114.0.2:6379/0
      - REDIS_CELERY=redis://10.114.0.2:6379/1
      - MONGO=mongodb://10.114.0.2:27017/
      - STATSD_HOST=graphite
    volumes:
      - /root/data/log:/log
    command: celery -A tsa.celery worker -l info -Q high_priority,default,query,low_priority -c 10
  graphite:
    image: graphiteapp/graphite-statsd
    restart: always
    ports:
      - 8088:80
