"""Initial state

Revision ID: 06850d25958a
Revises: 
Create Date: 2023-02-03 19:47:10.190176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06850d25958a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept',
    sa.Column('iri', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('iri')
    )
    op.create_table('dataset_distribution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ds', sa.String(), nullable=False),
    sa.Column('distr', sa.String(), nullable=False),
    sa.Column('relevant', sa.Boolean, nullable=True, default=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_endpoint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ds', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ddr',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('iri1', sa.String(), nullable=False),
    sa.Column('iri2', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('label',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('iri', sa.String(), nullable=False),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pure_subject',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('distribution_iri', sa.String(), nullable=False),
    sa.Column('subject_iri', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationship',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('group', sa.String(), nullable=False),
    sa.Column('candidate', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('robots_delay',
    sa.Column('iri', sa.String(), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('iri')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('robots_delay')
    op.drop_table('relationship')
    op.drop_table('pure_subject')
    op.drop_table('label')
    op.drop_table('ddr')
    op.drop_table('dataset_endpoint')
    op.drop_table('dataset_distribution')
    op.drop_table('concept')
    # ### end Alembic commands ###
