"""Added common in Relationship

Revision ID: 96edbcb9c734
Revises: 06850d25958a
Create Date: 2023-02-10 13:04:29.666294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "96edbcb9c734"
down_revision = "06850d25958a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("relationship", sa.Column("common", sa.String(), nullable=False))
    op.create_index(
        "relationship_index_common", "relationship", ["common"], postgresql_using="HASH"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("relationship_index_common", table_name="relationship")
    op.drop_column("relationship", "common")
    # ### end Alembic commands ###
